// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: IoAdaptLvglObjMsg

#ifndef _IOADAPTLVGLOBJMSG_UI_H
#define _IOADAPTLVGLOBJMSG_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_btnSample;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_lblPressure;
extern lv_obj_t * ui_sldZoom;
extern lv_obj_t * ui_arcPan;
extern lv_obj_t * ui_calSchedule;
extern lv_obj_t * ui____initial_actions0;






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
