// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: IoAdaptLvglObjMsg

#ifndef _IOADAPTLVGLOBJMSG_UI_H
#define _IOADAPTLVGLOBJMSG_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_btnSample;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_lblPressure;
extern lv_obj_t * ui_arcZoomX;
extern lv_obj_t * ui_sldZoomY;
extern lv_obj_t * ui_calSchedule;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
