// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: IoAdaptLvglObjMsg

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSample = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnSample, 92);
    lv_obj_set_height(ui_btnSample, 37);
    lv_obj_set_x(ui_btnSample, 169);
    lv_obj_set_y(ui_btnSample, 125);
    lv_obj_set_align(ui_btnSample, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSample, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSample, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_btnSample);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Sample");

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 16);
    lv_obj_set_y(ui_Label1, 19);
    lv_label_set_text(ui_Label1, "Pressure");

    ui_lblPressure = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblPressure, 176);
    lv_obj_set_height(ui_lblPressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPressure, 90);
    lv_obj_set_y(ui_lblPressure, 20);
    lv_label_set_text(ui_lblPressure, "");
    lv_obj_set_style_border_color(ui_lblPressure, lv_color_hex(0x640000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblPressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblPressure, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sldZoom = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_sldZoom, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldZoom) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldZoom, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_sldZoom, 10);
    lv_obj_set_height(ui_sldZoom, 100);
    lv_obj_set_x(ui_sldZoom, 344);
    lv_obj_set_y(ui_sldZoom, 20);

    ui_arcPan = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_arcPan, 85);
    lv_obj_set_height(ui_arcPan, 74);
    lv_obj_set_x(ui_arcPan, 168);
    lv_obj_set_y(ui_arcPan, -102);
    lv_obj_set_align(ui_arcPan, LV_ALIGN_CENTER);

    ui_calSchedule = lv_calendar_create(ui_Screen1);
    lv_obj_t * ui_calSchedule_header = lv_calendar_header_arrow_create(ui_calSchedule);
    lv_obj_set_width(ui_calSchedule, 226);
    lv_obj_set_height(ui_calSchedule, 220);
    lv_obj_set_x(ui_calSchedule, -109);
    lv_obj_set_y(ui_calSchedule, 1);
    lv_obj_set_align(ui_calSchedule, LV_ALIGN_CENTER);

}
